// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"
)

type Card struct {
	ID            int64          `json:"id"`
	Title         string         `json:"title"`
	Description   sql.NullString `json:"description"`
	Createdat     sql.NullTime   `json:"createdat"`
	Updatedat     sql.NullTime   `json:"updatedat"`
	Status        int64          `json:"status"`
	Completedat   sql.NullTime   `json:"completedat"`
	Estimatedmins int64          `json:"estimatedmins"`
	Trackedmins   int64          `json:"trackedmins"`
	Isactive      bool           `json:"isactive"`
	Projectid     int64          `json:"projectid"`
}

type Project struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	Createdat sql.NullTime `json:"createdat"`
}

type TimeEntry struct {
	ID        int64     `json:"id"`
	Cardid    int64     `json:"cardid"`
	Starttime time.Time `json:"starttime"`
	Endtime   time.Time `json:"endtime"`
	Duration  int64     `json:"duration"`
}

type UserProfile struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	Settings  string       `json:"settings"`
	Createdat sql.NullTime `json:"createdat"`
	Updatedat sql.NullTime `json:"updatedat"`
}
