// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"
)

type ArcherStat struct {
	ID        int64  `json:"id"`
	Userid    int64  `json:"userid"`
	Statname  string `json:"statname"`
	Statvalue int64  `json:"statvalue"`
}

type Card struct {
	ID            int64          `json:"id"`
	Title         string         `json:"title"`
	Description   sql.NullString `json:"description"`
	Createdat     sql.NullTime   `json:"createdat"`
	Updatedat     sql.NullTime   `json:"updatedat"`
	Status        int64          `json:"status"`
	Completedat   sql.NullTime   `json:"completedat"`
	Estimatedmins int64          `json:"estimatedmins"`
	Trackedmins   int64          `json:"trackedmins"`
	Isactive      bool           `json:"isactive"`
	Projectid     int64          `json:"projectid"`
}

type Project struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	Createdat sql.NullTime `json:"createdat"`
}

type ProjectSkill struct {
	ProjectID int64 `json:"project_id"`
	SkillID   int64 `json:"skill_id"`
}

type TaskCompletion struct {
	ID             int64     `json:"id"`
	Cardid         int64     `json:"cardid"`
	Userid         int64     `json:"userid"`
	Completiontime time.Time `json:"completiontime"`
	Baseexp        int64     `json:"baseexp"`
	Timebonusexp   int64     `json:"timebonusexp"`
	Streakbonusexp int64     `json:"streakbonusexp"`
	Totalexp       int64     `json:"totalexp"`
}

type TimeEntry struct {
	ID        int64     `json:"id"`
	Cardid    int64     `json:"cardid"`
	Starttime time.Time `json:"starttime"`
	Endtime   time.Time `json:"endtime"`
	Duration  int64     `json:"duration"`
}

type UserProfile struct {
	ID                 int64        `json:"id"`
	Name               string       `json:"name"`
	Settings           string       `json:"settings"`
	Createdat          sql.NullTime `json:"createdat"`
	Updatedat          sql.NullTime `json:"updatedat"`
	ProgressionPoints  int64        `json:"progressionPoints"`
	ArcherLevel        int64        `json:"archerLevel"`
	ArcherExperience   int64        `json:"archerExperience"`
	IdleResources      int64        `json:"idleResources"`
	LastLoginTimeStamp sql.NullTime `json:"lastLoginTimeStamp"`
}

type UserSkill struct {
	ID          int64          `json:"id"`
	UserID      int64          `json:"user_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type UserSkillProgress struct {
	ID                  int64         `json:"id"`
	UserID              int64         `json:"user_id"`
	SkillID             int64         `json:"skill_id"`
	TotalMinutesTracked sql.NullInt64 `json:"total_minutes_tracked"`
	LastUpdated         sql.NullTime  `json:"last_updated"`
}
