// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: progress_stats.sql

package database

import (
	"context"
	"database/sql"
)

const aggregateMonthHours = `-- name: AggregateMonthHours :one
SELECT CAST(IFNULL(SUM(te.duration), 0) AS FLOAT) AS totalTrackedMinsCurrentMonth
FROM TimeEntries te
JOIN Cards c ON te.cardId = c.id
JOIN Projects p ON c.projectId = p.id
WHERE p.id = ?
AND strftime('%Y-%m', te.startTime) = strftime('%Y-%m', 'now')
`

func (q *Queries) AggregateMonthHours(ctx context.Context, id int64) (float64, error) {
	row := q.db.QueryRowContext(ctx, aggregateMonthHours, id)
	var totaltrackedminscurrentmonth float64
	err := row.Scan(&totaltrackedminscurrentmonth)
	return totaltrackedminscurrentmonth, err
}

const aggregatePreviousMonthHours = `-- name: AggregatePreviousMonthHours :one
SELECT CAST(IFNULL(SUM(te.duration), 0) AS FLOAT) AS totalTrackedMinsPreviousMonth
FROM TimeEntries te
JOIN Cards c ON te.cardId = c.id
JOIN Projects p ON c.projectId = p.id
WHERE p.id = ?
AND strftime('%Y-%m', te.startTime) = strftime('%Y-%m', 'now', 'start of month', '-1 month')
`

func (q *Queries) AggregatePreviousMonthHours(ctx context.Context, id int64) (float64, error) {
	row := q.db.QueryRowContext(ctx, aggregatePreviousMonthHours, id)
	var totaltrackedminspreviousmonth float64
	err := row.Scan(&totaltrackedminspreviousmonth)
	return totaltrackedminspreviousmonth, err
}

const aggregatePreviousWeekHours = `-- name: AggregatePreviousWeekHours :one
SELECT CAST(IFNULL(SUM(te.duration), 0) AS FLOAT) AS totalTrackedMinsPreviousWeek
FROM TimeEntries te
JOIN Cards c ON te.cardId = c.id
JOIN Projects p ON c.projectId = p.id
WHERE p.id = ?
AND strftime('%Y-%W', te.startTime) = strftime('%Y-%W', 'now', '-7 days')
`

func (q *Queries) AggregatePreviousWeekHours(ctx context.Context, id int64) (float64, error) {
	row := q.db.QueryRowContext(ctx, aggregatePreviousWeekHours, id)
	var totaltrackedminspreviousweek float64
	err := row.Scan(&totaltrackedminspreviousweek)
	return totaltrackedminspreviousweek, err
}

const aggregateWeekHours = `-- name: AggregateWeekHours :one
SELECT CAST(IFNULL(SUM(te.duration), 0) AS FLOAT) AS totalTrackedMinsCurrentWeek
FROM TimeEntries te
JOIN Cards c ON te.cardId = c.id
JOIN Projects p ON c.projectId = p.id
WHERE p.id = ?
AND strftime('%Y-%W', te.startTime) = strftime('%Y-%W', 'now')
`

func (q *Queries) AggregateWeekHours(ctx context.Context, id int64) (float64, error) {
	row := q.db.QueryRowContext(ctx, aggregateWeekHours, id)
	var totaltrackedminscurrentweek float64
	err := row.Scan(&totaltrackedminscurrentweek)
	return totaltrackedminscurrentweek, err
}

const getDailyTotalMinutes = `-- name: GetDailyTotalMinutes :many
SELECT
    DATE(startTime) AS date,
    SUM(duration) AS total_minutes
FROM
    TimeEntries
WHERE
    startTime >= DATE('now', '-1 year')
GROUP BY
    DATE(startTime)
ORDER BY
    DATE(startTime)
`

type GetDailyTotalMinutesRow struct {
	Date         interface{}     `json:"date"`
	TotalMinutes sql.NullFloat64 `json:"total_minutes"`
}

func (q *Queries) GetDailyTotalMinutes(ctx context.Context) ([]GetDailyTotalMinutesRow, error) {
	rows, err := q.db.QueryContext(ctx, getDailyTotalMinutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDailyTotalMinutesRow
	for rows.Next() {
		var i GetDailyTotalMinutesRow
		if err := rows.Scan(&i.Date, &i.TotalMinutes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthlyProgress = `-- name: GetMonthlyProgress :one
SELECT COUNT(DISTINCT DATE(startTime)) AS progress_days
FROM TimeEntries
WHERE strftime('%Y-%m', startTime) = strftime('%Y-%m', 'now')
`

func (q *Queries) GetMonthlyProgress(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getMonthlyProgress)
	var progress_days int64
	err := row.Scan(&progress_days)
	return progress_days, err
}

const getPreviousMonthlyProgress = `-- name: GetPreviousMonthlyProgress :one
SELECT COUNT(DISTINCT DATE(startTime)) AS progress_days
FROM TimeEntries
WHERE strftime('%Y-%m', startTime) = strftime('%Y-%m', 'now', 'start of month', '-1 month')
`

func (q *Queries) GetPreviousMonthlyProgress(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getPreviousMonthlyProgress)
	var progress_days int64
	err := row.Scan(&progress_days)
	return progress_days, err
}

const getPreviousWeeklyProgress = `-- name: GetPreviousWeeklyProgress :one
SELECT COUNT(DISTINCT DATE(startTime)) AS progress_days
FROM TimeEntries
WHERE strftime('%Y-%W', startTime) = strftime('%Y-%W', 'now', '-7 days')
`

func (q *Queries) GetPreviousWeeklyProgress(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getPreviousWeeklyProgress)
	var progress_days int64
	err := row.Scan(&progress_days)
	return progress_days, err
}

const getWeeklyProgress = `-- name: GetWeeklyProgress :one
SELECT COUNT(DISTINCT DATE(startTime)) AS progress_days
FROM TimeEntries
WHERE strftime('%Y-%W', startTime) = strftime('%Y-%W', 'now')
`

func (q *Queries) GetWeeklyProgress(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getWeeklyProgress)
	var progress_days int64
	err := row.Scan(&progress_days)
	return progress_days, err
}
