// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCard(arg1, arg2, arg3) {
  return window['go']['service']['cardService']['AddCard'](arg1, arg2, arg3);
}

export function Cleanup() {
  return window['go']['service']['cardService']['Cleanup']();
}

export function DeleteCard(arg1, arg2) {
  return window['go']['service']['cardService']['DeleteCard'](arg1, arg2);
}

export function GetActiveTimeEntry(arg1, arg2) {
  return window['go']['service']['cardService']['GetActiveTimeEntry'](arg1, arg2);
}

export function GetAll(arg1, arg2) {
  return window['go']['service']['cardService']['GetAll'](arg1, arg2);
}

export function GetCardById(arg1, arg2) {
  return window['go']['service']['cardService']['GetCardById'](arg1, arg2);
}

export function GetOpenCards(arg1) {
  return window['go']['service']['cardService']['GetOpenCards'](arg1);
}

export function StartCard(arg1, arg2) {
  return window['go']['service']['cardService']['StartCard'](arg1, arg2);
}

export function StopCard(arg1, arg2) {
  return window['go']['service']['cardService']['StopCard'](arg1, arg2);
}

export function UpdateCard(arg1, arg2, arg3) {
  return window['go']['service']['cardService']['UpdateCard'](arg1, arg2, arg3);
}

export function UpdateCardStatus(arg1, arg2, arg3) {
  return window['go']['service']['cardService']['UpdateCardStatus'](arg1, arg2, arg3);
}
