// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';
import {service} from '../models';

export function GetDailyTotalMinutes():Promise<Array<database.GetDailyTotalMinutesRow>>;

export function GetStats():Promise<service.GetStatsResult>;
