// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDailyTotalMinutes() {
  return window['go']['service']['progressService']['GetDailyTotalMinutes']();
}

export function GetStats() {
  return window['go']['service']['progressService']['GetStats']();
}
