// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllSettings():Promise<any>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;
