// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllSettings() {
  return window['go']['service']['settingService']['GetAllSettings']();
}

export function SetSetting(arg1, arg2) {
  return window['go']['service']['settingService']['SetSetting'](arg1, arg2);
}
