// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export enum CardStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    Todo = 0,
    Done = 1,
    Active = 2,
};

export class GetStatsResult {
    "weekHrs": StatCardData;
    "monthHrs": StatCardData;
    "weekProgress": StatCardData;
    "monthProgress": StatCardData;

    /** Creates a new GetStatsResult instance. */
    constructor($$source: Partial<GetStatsResult> = {}) {
        if (!("weekHrs" in $$source)) {
            this["weekHrs"] = (new StatCardData());
        }
        if (!("monthHrs" in $$source)) {
            this["monthHrs"] = (new StatCardData());
        }
        if (!("weekProgress" in $$source)) {
            this["weekProgress"] = (new StatCardData());
        }
        if (!("monthProgress" in $$source)) {
            this["monthProgress"] = (new StatCardData());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetStatsResult instance from a string or object.
     */
    static createFrom($$source: any = {}): GetStatsResult {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("weekHrs" in $$parsedSource) {
            $$parsedSource["weekHrs"] = $$createField0_0($$parsedSource["weekHrs"]);
        }
        if ("monthHrs" in $$parsedSource) {
            $$parsedSource["monthHrs"] = $$createField1_0($$parsedSource["monthHrs"]);
        }
        if ("weekProgress" in $$parsedSource) {
            $$parsedSource["weekProgress"] = $$createField2_0($$parsedSource["weekProgress"]);
        }
        if ("monthProgress" in $$parsedSource) {
            $$parsedSource["monthProgress"] = $$createField3_0($$parsedSource["monthProgress"]);
        }
        return new GetStatsResult($$parsedSource as Partial<GetStatsResult>);
    }
}

export class StatCardData {
    "value": number;
    "prevValue": number;

    /** Creates a new StatCardData instance. */
    constructor($$source: Partial<StatCardData> = {}) {
        if (!("value" in $$source)) {
            this["value"] = 0;
        }
        if (!("prevValue" in $$source)) {
            this["prevValue"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StatCardData instance from a string or object.
     */
    static createFrom($$source: any = {}): StatCardData {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StatCardData($$parsedSource as Partial<StatCardData>);
    }
}

export class UpdateCardParams {
    "title": string;
    "estimatedMins": number;
    "description": string;

    /** Creates a new UpdateCardParams instance. */
    constructor($$source: Partial<UpdateCardParams> = {}) {
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("estimatedMins" in $$source)) {
            this["estimatedMins"] = 0;
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateCardParams instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateCardParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateCardParams($$parsedSource as Partial<UpdateCardParams>);
    }
}

// Private type creation functions
const $$createType0 = StatCardData.createFrom;
