// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export enum CardStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    Todo = 0,
    Done = 1,
    Active = 2,
};

export class GetStatsResult {
    "weekHrs": number;
    "monthHrs": number;
    "yearHrs": number;

    /** Creates a new GetStatsResult instance. */
    constructor($$source: Partial<GetStatsResult> = {}) {
        if (!("weekHrs" in $$source)) {
            this["weekHrs"] = 0;
        }
        if (!("monthHrs" in $$source)) {
            this["monthHrs"] = 0;
        }
        if (!("yearHrs" in $$source)) {
            this["yearHrs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetStatsResult instance from a string or object.
     */
    static createFrom($$source: any = {}): GetStatsResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GetStatsResult($$parsedSource as Partial<GetStatsResult>);
    }
}

export class UpdateCardParams {
    "title": string;
    "estimatedMins": number;
    "description": string;

    /** Creates a new UpdateCardParams instance. */
    constructor($$source: Partial<UpdateCardParams> = {}) {
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("estimatedMins" in $$source)) {
            this["estimatedMins"] = 0;
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateCardParams instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateCardParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateCardParams($$parsedSource as Partial<UpdateCardParams>);
    }
}
