// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as database$0 from "../database/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetDailyTotalMinutes(): Promise<database$0.GetDailyTotalMinutesRow[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(111442708) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType1($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function GetStats(): Promise<$models.GetStatsResult> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1092713905) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType2($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function GetTotalExpForUser(): Promise<number> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3476611633) as any;
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = database$0.GetDailyTotalMinutesRow.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.GetStatsResult.createFrom;
