name: Wails build

on:
  workflow_dispatch:
  push:
    tags:
    # Match any new tag
      - '*'
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'

      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Build Wails app
        run: |
          wails build --platform ${{ matrix.platform.build_platform }} -o build/${{ matrix.platform.name }}-app

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Wails-${{ matrix.platform.name }}-build
          path: build/${{ matrix.platform.name }}-app/*
